[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sla"
version = "0.5.0"
description = "RAG-based Scientific Literature Assistant"
requires-python = ">=3.12"
dependencies = [
    "docling",
    "numpy",
    "ollama",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]

[tool.setuptools.packages.find]
where = ["src"]